import Mathlib

/-!
# Bigraded corank: algebraic-independence tower factorization

This file formalizes the exact field-algebra core of
`bigraded-corank-dss-cross.md` §G.  It does not formalize prime logarithms,
Stieltjes constants, infinite corank, exponential motives, or DSS-cross itself.

The theorem says that a disjoint union of two families is algebraically
independent over a base field precisely when the first family is algebraically
independent over the base field and the second family is algebraically
independent over the field generated by the first.
-/

namespace GaloisForLFunctions

noncomputable section

/-- **Bigraded corank §G: tower factorization.** For families `x` and `y` in a
field extension `E/F`, algebraic independence of the disjoint union
`Sum.elim y x` is equivalent to algebraic independence of `x` over `F` together
with algebraic independence of `y` over the generated field `F(x)`.

This is the Lean form of the paper proof's tower law:
joint independence is the regular apex plus the relative apex over the regular
field. -/
theorem algebraicIndependent_sumElim_intermediateField_iff
    {F E : Type*} {ι ι' : Type*} [Field F] [Field E] [Algebra F E]
    (x : ι → E) (y : ι' → E) :
    AlgebraicIndependent F (Sum.elim y x) ↔
      AlgebraicIndependent F x ∧
        AlgebraicIndependent (IntermediateField.adjoin F (Set.range x)) y := by
  rw [AlgebraicIndependent.sumElim_iff]
  exact and_congr_right fun _ => (IntermediateField.algebraicIndependent_adjoin_iff).symm

end

end GaloisForLFunctions
