import Mathlib

/-!
# Abelian holonomy from commuting monodromy generators

This file isolates the Tier-A group-theory core behind the §76/§77 "abelian
holonomy" discussion: if the prime-lattice monodromy generators commute, then
the holonomy subgroup they generate is abelian. It also records the representation
form: the image of a group homomorphism out of a commutative group is abelian.

No Picard-Vessiot existence theorem, Tannakian Galois correspondence, Zariski
closure, or infinite prime-lattice limit is asserted here.
-/

namespace GaloisForLFunctions

/-- **Image of an abelian lattice has abelian holonomy.** If the source group is
commutative, then every two elements in the range of a group homomorphism commute.
This is the Lean-safe core of the statement "the image of the free abelian prime
lattice under a holonomy representation is abelian." -/
theorem monoidHom_range_commutative {Γ G : Type*} [CommGroup Γ] [Group G] (ρ : Γ →* G) :
    ∀ x ∈ ρ.range, ∀ y ∈ ρ.range, Commute x y := by
  intro x hx y hy
  rw [MonoidHom.mem_range] at hx hy
  rcases hx with ⟨a, rfl⟩
  rcases hy with ⟨b, rfl⟩
  rw [commute_iff_eq]
  simpa using congrArg ρ (mul_comm a b)

/-- **Commuting monodromy generators generate an abelian holonomy subgroup.** If
the chosen per-prime generators commute pairwise, then every two elements of the
subgroup generated by them commute. This is the group-theory core of the finite
"commuting monodromies imply abelian image" firewall. -/
theorem closure_range_commutative_of_pairwise_commute {ι G : Type*} [Group G] (g : ι → G)
    (hcomm : ∀ i j, Commute (g i) (g j)) :
    ∀ x ∈ Subgroup.closure (Set.range g), ∀ y ∈ Subgroup.closure (Set.range g), Commute x y := by
  intro x hx y hy
  refine Subgroup.closure_induction₂ (k := Set.range g) (p := fun x y _ _ => Commute x y) ?mem
    ?one_left ?one_right ?mul_left ?mul_right ?inv_left ?inv_right hx hy
  · intro x y hx hy
    rcases hx with ⟨i, rfl⟩
    rcases hy with ⟨j, rfl⟩
    exact hcomm i j
  · intro x _hx
    exact Commute.one_left x
  · intro x _hx
    exact Commute.one_right x
  · intro _x _y _z _hx _hy _hz hxz hyz
    exact hxz.mul_left hyz
  · intro _y _z _x _hy _hz _hx hxy hxz
    exact hxy.mul_right hxz
  · intro _x _y _hx _hy hxy
    exact hxy.inv_left
  · intro _x _y _hx _hy hxy
    exact hxy.inv_right

end GaloisForLFunctions
