import JensenLadder.RHReduction
import Mathlib.Tactic

/-!
# Amenability is a no-go, not a proof (Euler-blindness / DH-replay)

A recurring tempting "proof" of RH (the *amenability argument*) runs:

1. the prime dynamics is generated by the `ax+b` group `P = ℚ^×_{>0} ⋉ ℚ`, an
   extension of abelian groups, hence solvable, hence **amenable**;
2. (Kesten) the regular representation of an amenable group has spectral radius
   equal to the norm — **no spectral gap**, `C^*(G)=C^*_r(G)`;
3. an off-line zero is an isolated `L²` bound state of the prime operator
   `D = A_∞ − Σ_p σ_p`;
4. amenability forbids such bound states, so there are no off-line zeros: RH.

This argument fails for two independent reasons, each captured here as a
machine-checked logical fact:

* **Euler-blindness ⇒ DH-replay.** Amenability is a property of the *group*,
  shared by every L-function built on the same adele-class scaling structure —
  in particular by the Davenport–Heilbronn function, which has the same
  functional equation, the same reality, and the same `ax+b` dynamics, **but has
  zeros off the critical line**. Any criterion that forces reality of regular
  zeros from such shared structure *alone* would force it for the DH fake too,
  contradicting the DH off-line zero. So amenability cannot separate `ζ` from a
  fake — it is the same wall as `DHMultiplicityFakeGate` /
  `AbsoluteBudgetFakeFamilyBlindness`. (This is also why generic
  operator-algebraic positivity, such as relative entropy or Casini–Bekenstein
  transfer, cannot prove RH: it is universal, hence DH-replayable.)

* **No-gap ≠ no-point-spectrum.** Step 2 delivers absence of a spectral *gap*;
  step 4 needs absence of *point spectrum*. These are different. The
  almost-Mathieu operator on the amenable group `ℤ` (coupling `λ>1`, Anderson
  localization) has gapless essential spectrum yet **pure-point** spectrum — so
  "amenable ⇒ no point spectrum" is a non-sequitur, and "off-line zero = `L²`
  bound state" is itself the conjectural Connes/Koopman bridge, not a theorem.

The genuinely proven residue is the *positive* reading already in the atlas:
amenability of the abelian Euler group `⊕_p ℤ` ⇒ **no spectral gap = the
no-margin** (cf. `ResolutionWall`). That says RH is *hard* (marginless), not that
RH is *true*. The RH content is the self-dual `λ=1` criticality supplied by the
functional equation, which amenability does not deliver.

The useful residue is a no-go: amenability explains gaplessness/no-margin, not
the source-built positivity or fake-family separator needed for RH.
-/

namespace JensenLadder
namespace AmenabilityNoGo

open Complex

/-- **Euler-blindness ⇒ no reality gate (the core no-go).**

A criterion is *Euler-blind* if it forces reality of the regular zeros of an
L-datum from structure it shares with every member of the fake family — formally,
a single hypothesis `C` together with a gate that produces reality `∀ z, P z →
z.im = 0` for **any** zero-predicate `P`, without inspecting which L-function `P`
describes.  Amenability of the `ax+b`/`⊕_p ℤ` scaling group is exactly such a `C`.

No such criterion can exist: instantiate `P` at the Davenport–Heilbronn fake,
which has a regular zero `w` off the line (`w.im ≠ 0`).  The blind gate would
force `w.im = 0`, a contradiction.  Hence amenability (and any universal
operator-algebraic property) is a no-go for RH. -/
theorem no_eulerBlind_reality_gate
    {C : Prop} (hC : C)
    (blindGate : ∀ P : ℂ → Prop, C → ∀ z : ℂ, P z → z.im = 0)
    {DHRegularZero : ℂ → Prop} (w : ℂ)
    (hw : DHRegularZero w) (hwoff : w.im ≠ 0) : False :=
  hwoff (blindGate DHRegularZero hC w hw)

/-- The same statement phrased against the project's actual RH endpoint: an
Euler-blind criterion cannot even certify reality of the regular `Ξ`-zeros,
because the *identical* blind gate fails on the DH fake. -/
theorem eulerBlind_cannot_certify_riemannXi
    {C : Prop} (hC : C)
    (blindGate : ∀ P : ℂ → Prop, C → ∀ z : ℂ, P z → z.im = 0)
    {DHRegularZero : ℂ → Prop} (w : ℂ)
    (hw : DHRegularZero w) (hwoff : w.im ≠ 0) :
    ¬ (C → ∀ z : ℂ, RHReduction.riemannXiRegularZero z → z.im = 0) := by
  intro _
  exact no_eulerBlind_reality_gate hC blindGate w hw hwoff

/-- **No-gap ≠ no-point-spectrum (the Step-4 non-sequitur).**

Amenability (Kesten) gives "no spectral gap"; the argument needs "no point
spectrum".  The schematic implication `noGap → noPointSpectrum` is invalid — it
fails for the almost-Mathieu operator on the amenable group `ℤ` (`λ>1`: gapless
essential spectrum, yet pure-point).  We record the logical invalidity: there is
no proof of `noGap → noPointSpectrum` uniform in the two propositions. -/
theorem noGap_not_implies_noPointSpectrum :
    ¬ ∀ noGap noPointSpectrum : Prop, noGap → noPointSpectrum := by
  intro h
  exact h True False trivial

/-- **Surviving content (positive, RH-agnostic).**  What amenability *does* give
is the no-margin: amenability ⇒ no spectral gap.  Here `noGap` and `noMargin`
are the *same* proposition (Kesten: spectral radius = norm = gaplessness), so the
implication is a tautology — it carries no RH content, exactly matching
`ResolutionWall`'s "the wall is real, the crossing is not". -/
theorem amenable_gives_noMargin
    {amenable noGap : Prop} (h : amenable → noGap) : amenable → noGap := h

end AmenabilityNoGo
end JensenLadder
